const categoryTranslations = {
  "Arts & Entertainment": "Konst och underhållning",
  Industry: "Industri",
  "Innovation & Tech": "Innovation & Teknik",
  Life: "Livet",
  Society: "Samhället"
};

const topics = [
  "Art",
  "Beauty",
  "Books",
  "Comics",
  "Culture",
  "Fiction",
  "Film",
  "Food",
  "Gaming",
  "Humor",
  "Music",
  "Photography",
  "Podcasts",
  "Poetry",
  "Social Media",
  "Sports",
  "Style",
  "TV",
  "Writing",
  "Business",
  "Design",
  "Economy",
  "Freelancing",
  "Leadership",
  "Marketing",
  "Product Management",
  "Productivity",
  "Startups",
  "Venture Capital",
  "Work",
  "Accessibility",
  "Android Dev",
  "Artificial Intelligence",
  "Blockchain",
  "Cryptocurrency",
  "Cybersecurity",
  "Data Science",
  "Digital Life",
  "Gadgets",
  "Javascript",
  "Machine Learning",
  "Math",
  "Neuroscience",
  "Programming",
  "Science",
  "Self-Driving Cars",
  "Software Engineering",
  "Space",
  "Technology",
  "UX",
  "Visual Design",
  "iOS Dev",
  "Addiction",
  "Creativity",
  "Disability",
  "Family",
  "Health",
  "Lifestyle",
  "Mental Health",
  "Mindfulness",
  "Money",
  "Parenting",
  "Pets",
  "Psychology",
  "Relationships",
  "Self",
  "Travel",
  "Cities",
  "Education",
  "Environment",
  "Equality",
  "Future",
  "History",
  "Immigration",
  "Justice",
  "Language",
  "Media",
  "Philosophy",
  "Politics",
  "Privacy",
  "Race",
  "Religion",
  "Transportation"
];

const topicsTranslated = [
  "Konst",
  "Skönhet",
  "Böcker",
  "Serier",
  "Kultur",
  "Fiktion",
  "Filma",
  "Mat",
  "Gaming",
  "Humör",
  "Musik",
  "Fotografi",
  "Podcaster",
  "Poesi",
  "Sociala media",
  "Sporter",
  "Stil",
  "TV",
  "Skrift",
  "Företag",
  "Design",
  "Ekonomi",
  "Frilans",
  "Ledarskap",
  "Marketing",
  "Produktledning",
  "Produktivitet",
  "Startups",
  "Venture Capital",
  "Arbete",
  "Tillgänglighet",
  "Android Dev",
  "Artificiell intelligens",
  "Blockchain",
  "Kryptovaluta",
  "Cybersäkerhet",
  "Data Science",
  "Digital Life",
  "gadgets",
  "JavaScript",
  "Maskininlärning",
  "Matematik",
  "Neuroscience",
  "Programmering",
  "Vetenskap",
  "Självgående bilar",
  "Mjukvaruutveckling",
  "Rymden",
  "Teknologi",
  "UX",
  "Visual Design",
  "IOS Dev",
  "Missbruk",
  "Kreativitet",
  "Handikapp",
  "Familj",
  "Hälsa",
  "Lifestyle",
  "Mental hälsa",
  "Mindfulness",
  "Pengar",
  "Föräldraskap",
  "Husdjur",
  "Psykologi",
  "Relationer",
  "Själv",
  "Resa",
  "Cities",
  "Utbildning",
  "Miljö",
  "Jämlikhet",
  "Framtida",
  "Historia",
  "Invandring",
  "Rättvisa",
  "Språk",
  "Media",
  "Filosofi",
  "Politik",
  "Integritet",
  "Lopp",
  "Religion",
  "Transport"
];

function makeTranslationObj() {
  const translations = {};

  topics.forEach(topic => {
    translations[topic] = topicsTranslated[topics.indexOf(topic)];
  });

  console.log(translations);
}

makeTranslationObj();
